### ISSUE TITLE
Error Class 'Transbank\Webpay\WebpayPlus\Transaction' not found 

### ISSUE THREAD

**Issue by betomedin** [TransbankDevelopers/transbank-sdk-php-webpay-rest-example#24]
Al momento de ejecutar createdTransaction() de WebpayController

**Comment by gonzunigad** [comment]
Hola! ¿En que momento te aparece ese error?  Al menos he probado ahora y no veo problemas.

**Comment by betomedin** [comment]
Perdón se me olvidó cerrar esto, al final descubrí que era un error mío. Gracias.
